name: Deploy to VPS

on:
  push:
    branches:
      - main  # Adjust this to your branch if needed

jobs:
  deploy:
    runs-on: ubuntu-latest  # The job will run on a virtual Ubuntu environment

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # This will check out your repository's code

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.5.3  # Sets up SSH authentication
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # Add the private SSH key from GitHub Secrets

    - name: Deploy to VPS
      run: |
        # Ensure SSH can connect without strict host key checking
        ssh -o StrictHostKeyChecking=no root@103.168.18.92 -p 7576 << 'EOF'
          # Navigate to the app directory
          cd /var/www/tclbackend || exit 1  # Make sure the directory exists

          # Pull the latest changes from your GitHub repository
          git pull origin main  # Adjust if you are using a different branch

          # Install or update dependencies
          npm install

          # Restart the app using the full path to pm2
          /root/.nvm/versions/node/v22.14.0/bin/pm2 restart expressjs  # Replace with the correct app name

        EOF
